version: '3.1'

services:
  web:
    image: s3dt-catalog
    command: ["gunicorn", "-b", "0.0.0.0:80", "app:app", "--log-file", "-"]
    ports: ["8002:80"]
    volumes:
    - .:/opt/s3dt-catalog
    environment:
    - REDIS_URL=redis://redis:6379/
    - MONGO_URI=mongodb://mongo/s3dt_catalog
    depends_on:
    - worker
    - redis
    - mongo
    restart: always
  worker:
    image: s3dt-catalog
    command: ["python", "-u", "worker.py"]
    volumes:
    - .:/opt/s3dt-catalog
    environment:
    - REDIS_URL=redis://redis:6379/
    - MONGO_URI=mongodb://mongo/s3dt_catalog
    - SHOPTET_CATALOG_URI
    - ED_CATALOG_URI
    - ED_LOGIN
    - ED_PASSWORD
    depends_on:
    - redis
    - mongo
    restart: always
  mongo:
    image: mongo
    command: --smallfiles
    restart: always
  redis:
    image: redis
    restart: always
